apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: production
  annotations:
    # Configure Application Load Balancer parameters
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    
    # Enable ports 80 (HTTP) and 443 (HTTPS)
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    
    # Reference ACM Certificate
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:626635412838:certificate/6da74523-4c83-4f34-92c4-1d1151c1fdb8
    
    # Automatically redirect HTTP to HTTPS
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb # Standard ingress class definition
  rules:
    - http:
        paths:
          # Route all HTTP traffic directly to our ClusterIP service
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
